Update Deployment.yml

diff --git a/.github/workflows/Deployment.yml b/.github/workflows/Deployment.yml
--- a/.github/workflows/Deployment.yml
+++ b/.github/workflows/Deployment.yml
@@ -11,10 +11,10 @@ jobs:
 
     steps:
       - name: Check out code
-        uses: actions/checkout@v3  # 최신 버전 사용
+        uses: actions/checkout@v3
 
       - name: Set up JDK 21
-        uses: actions/setup-java@v4
+        uses: actions/setup-java@v3
         with:
           java-version: '21'
           distribution: 'temurin'
@@ -41,7 +41,7 @@ jobs:
       - name: Deploy to EC2
         env:
           EC2_HOST: ${{ secrets.EC2_HOST }}
-          EC2_USER: ${{ secrets.EC2_USER }}
+          EC2_USER: ubuntu
           EC2_KEY: ${{ secrets.EC2_KEY }}
         run: |
           mkdir -p ~/.ssh
@@ -49,6 +49,6 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
           echo "Deploying $executable_jar to EC2"
-          scp -o StrictHostKeyChecking=no $executable_jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.jar || { echo 'Failed to copy jar'; exit 1; }
-          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "pkill -f 'java -jar' || echo 'No running app to kill'"
-          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "nohup java -jar /home/$EC2_USER/app.jar > /dev/null 2>&1 &" || { echo 'Failed to start app'; exit 1; }
+          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $executable_jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.jar || { echo 'Failed to copy jar'; exit 1; }
+          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USER@$EC2_HOST "pkill -f 'java -jar' || echo 'No running app to kill'"
+          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USER@$EC2_HOST "nohup java -jar /home/$EC2_USER/app.jar > /dev/null 2>&1 &" || { echo 'Failed to start app'; exit 1; }
